Feature darya firebase
ToDoInThreeMonth/ToDoIn pull request #9
Opened 2021-05-17 07:20 UTC by tatarinova0903

2021-05-22 11:54 UTC, blackplayerten requested changes

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Controller/AuthController.swift
> +    struct LayersConstants {
private

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +        let error = validateInput(email: email, name: name, password1: password1, password2: password2, isSignIn: false)
если это валидация типа: пароль меньше 8 символов, не совпадают, то это нужно в presenter вынести

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +    private init() {}
зачем тогда?)

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +            completion(.failure(error))
наверное нужен switch по ошибке, чтобы пользователю показывать какого рода ошибка произошла

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +
тоже в presenter

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +            print("Error signing out: %@", signOutError)
лучше отправлять на верх слоям, чтобы алертом/попапом показать пользователю

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Presenter/AccountPresenter.swift
> +        groupsManager.observeUser(by: nil) { [weak self] (result) in
guard let self = self else { return }

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Presenter/AccountPresenter.swift
> +        friends = []
зачем? у тебя в классе уже поле друзей есть

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Presenter/AccountPresenter.swift
> +        authManager.signOut()
а если ошибка?

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Account/Presenter/AuthPresenter.swift
> +        let email = authView?.getEmail() ?? ""
раскрыть опционал

2021-05-22 11:54 UTC, blackplayerten commented on ToDoIn/ToDoIn/Groups/Controllers/GroupController.swift
> +        let owner = presenter?.getUser(by: section).name ?? ""
не очень грузить данные в ячейке

2021-05-23 13:23 UTC, tatarinova0903 commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +    private init() {}
Чтобы синглтон создать

2021-05-23 13:27 UTC, tatarinova0903 commented on ToDoIn/ToDoIn/Account/Model/AuthManager.swift
> +            completion(.failure(error))
разные и показываются, там у меня свой CustomError прописан, и validateInput возвращает один из customError'ов, которые в комплишене и отображаются в зависимости от того, что за ошибка

2021-05-24 13:45 UTC, merged